### ISSUE TITLE
When will upstream integration happen?

### ISSUE THREAD

**Issue by schulmar** [mikael-s-persson/templight#29] opened 2016-01-19 12:18 UTC
Is there a plan when templight will be integrated into upstream clang?
What are the necessary steps to do so and how far is the progress of these?

**Comment by r0mai** [comment] 2016-01-19 13:16
Yes there is. There is an open review for this patch to clang here: http://reviews.llvm.org/D5767

As far as I know, the main and only thing missing is good test coverage for the functionality.
@sabel83 and I had some work on this last year and wrote some very simple (but not exhaustive) tests.

You can check this work here:
https://github.com/llvm-mirror/clang/compare/master...sabel83:templight

We plan to get back on this and push this upstream.

**Comment by wichtounet** [comment] 2016-01-25 09:00
Am I understanding correctly that the patch only adds the base class that is then used by templight ? 

So the only that would change for templight is that it won't be necessary to patch clang but it would still be necessary to build templight inside clang sources, right ? Or templight would be able to build simply with libclang ?

**Comment by r0mai** [comment] 2016-01-25 14:05
Partly yes.
The current patch has some default, basic capability to output the trace into a yaml format. See https://github.com/mikael-s-persson/templight/blob/5c944a52ee1f0b27a114a938aef64fe5e546741b/templight_clang_patch.diff#L526

This was needed to create the automated tests for templight. Of course, it can used for your own purposes.

For the more efficient protobuf output format you'll need the extra templight plugin, and that'll probably require a new build of clang.

It might be possible to do this in a way that don't require recompilation and templight could somehow attach itself to libclang. I'm not sure what are the rules for extending the libclang API, or otherwise what kind of complications it would introduce in the templight code.

**Comment by wichtounet** [comment] 2016-01-25 15:05
Thanks a lot for the clarifications :)

**Comment by mikael-s-persson** [comment] 2016-01-25 20:30
Basically, the patch is designed to minimize the impact on the mainline
clang build, so that the distributions of clang won't contain all the
templight code, only the few hooks needed by templight. Templight would
then be built as a tool, compiled against the clang source, similar to how
other clang tools work, such as iwyu (if memory servese right). It could
then be distributed like other clang tools, via a tool sub-repo of the
clang source repo and as binary distribution on deb / rpm.

This was the only viable compromise between relying on libclang (which
would be convenient, but is unfortunately not possible because of how deep
the templight hooks need to be placed) and baking the templight code
directly into clang (which would go against clang development policies and
guidelines).

**Comment by badair** [comment] 2016-02-24 13:12
FWIW, I made some quick-and-dirty changes to the Clang patch from Templight commit 4da951ef9a5a5130e33c62ba98b75ab7480edf2b. Lightly tested on Clang revision 261701, via templight-cl on Windows.

The one regression in this patch is a presumable crash if the program name exceeds the system limit. they renamed the method to check for this, and added a parameter. It will be easy to fix that, I just didn't need it for personal use.

I assume you don't want this in a PR, but I thought it would be useful to others: http://pastebin.com/chKb01kV

**Comment by arrowd** [comment] 2017-05-06 18:33
So, any chance the upstreaming would happen?

**Comment by HadrienG2** [comment] 2018-02-12 08:13
Well, it looks like the clang patch mentioned above, which integrates the hooks needed for templight into clang, got finally merged! So perhaps this ticket can be closed now.

**Comment by r0mai** [comment] 2018-02-13 17:48
http://reviews.llvm.org/D5767 has been merged

**Closed by r0mai** 2018-02-13 17:48 UTC

**Comment by Trass3r** [comment] 2018-02-14 13:55
Needed to change the following though for it to compile:
```diff
 TemplightDebugger.cpp | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/TemplightDebugger.cpp b/TemplightDebugger.cpp
index efce074..b13dcfd 100644
--- a/TemplightDebugger.cpp
+++ b/TemplightDebugger.cpp
@@ -369,8 +369,8 @@ public:
   void LookupInDeclContext(DeclContext* decl, bool shouldGoUp = false) {
     DeclContext* cur_decl = decl;
     while(cur_decl) {
-      for(DeclContext::all_lookups_iterator it = cur_decl->lookups_begin(), 
-          it_end = cur_decl->lookups_end(); it != it_end; ++it) {
+      for(DeclContext::all_lookups_iterator it = cur_decl->lookups().begin(), 
+          it_end = cur_decl->lookups().end(); it != it_end; ++it) {
         if(QueryReg.match(it.getLookupName().getAsString())) {
           for(DeclContext::lookup_result::iterator ri = (*it).begin(), 
               ri_end = (*it).end(); ri != ri_end; ++ri) {
 CMakeLists.txt | 1 +
 1 file changed, 1 insertion(+)

diff --git a/CMakeLists.txt b/CMakeLists.txt
index ccaf0fc..d6b1f8c 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -27,6 +27,7 @@ add_clang_executable(templight
   )
 
 target_link_libraries(templight
+  PRIVATE
   clangBasic
   clangFrontend
   clangFrontendTool
```
